CONSENT_TYPE_PERSONAL_DATA_PROCESSING = "personal_data_processing"
CONSENT_TYPE_PRIVACY_POLICY_ACKNOWLEDGEMENT = "privacy_policy_acknowledgement"
CONSENT_TYPE_SAINT_PETERSBURG_ACKNOWLEDGEMENT = "saint_petersburg_acknowledgement"

CONSENT_TYPES = (
    CONSENT_TYPE_PERSONAL_DATA_PROCESSING,
    CONSENT_TYPE_PRIVACY_POLICY_ACKNOWLEDGEMENT,
    CONSENT_TYPE_SAINT_PETERSBURG_ACKNOWLEDGEMENT,
)

SAINT_PETERSBURG_ACKNOWLEDGEMENT_TEXT = (
    "Я понимаю, что подаю заявку на вступление в ложу, работающую в Санкт-Петербурге"
)

EMAIL_OUTBOX_EVENT_CANDIDATE_APPLICATION_RECEIVED = "candidate_application_received"
EMAIL_OUTBOX_EVENT_TYPES = (EMAIL_OUTBOX_EVENT_CANDIDATE_APPLICATION_RECEIVED,)

EMAIL_OUTBOX_STATUS_PENDING = "pending"
EMAIL_OUTBOX_STATUS_PROCESSING = "processing"
EMAIL_OUTBOX_STATUS_SENT = "sent"
EMAIL_OUTBOX_STATUS_FAILED = "failed"
EMAIL_OUTBOX_STATUSES = (
    EMAIL_OUTBOX_STATUS_PENDING,
    EMAIL_OUTBOX_STATUS_PROCESSING,
    EMAIL_OUTBOX_STATUS_SENT,
    EMAIL_OUTBOX_STATUS_FAILED,
)
